const builtins=[
  {name:'Big Applause',sub:'Strong audience',icon:'ðŸ‘',file:'sounds/applause-strong.wav',color:'#ff4d2e'},
  {name:'Quick Applause',sub:'Small group',icon:'ðŸ™Œ',file:'sounds/applause-small.wav',color:'#ff8a4c'},
  {name:'Standing Ovation',sub:'End-of-show crowd',icon:'ðŸ†',file:'sounds/applause-show.wav',color:'#ffbf47'},
  {name:'Sarcastic Clap',sub:'One-person clap',icon:'ðŸ˜',file:'sounds/sarcastic-clap.wav',color:'#9f7aea'},
  {name:'Boo!',sub:'Unhappy crowd',icon:'ðŸ‘Ž',type:'boo',color:'#d96c9d'},
  {name:'Laughter',sub:'Real crowd laugh',icon:'ðŸ˜‚',file:'sounds/laughter.wav',color:'#50d890'},
  {name:'Fog Horn',sub:'Deep blast',icon:'ðŸ“£',type:'horn',color:'#56b6ff'},
  {name:'Buzzer',sub:'Wrong answer',icon:'ðŸš¨',file:'sounds/buzzer.wav',color:'#ff4d2e'},
  {name:'Weeee... SPLAT!',sub:'Falling comedy hit',icon:'W!',type:'splat',color:'#e85d3f'},
  {name:'Air Horn',sub:'Big live-show blast',icon:'AH',type:'airhorn',color:'#f5b942'},
  {name:'Rimshot',sub:'Ba-dum-tss',icon:'DR',type:'rimshot',color:'#ef3e33'},
  {name:'Crowd Gasp',sub:'Shocked reaction',icon:'!!',type:'gasp',color:'#9f7aea'},
  {name:'Record Scratch',sub:'Stop the show',icon:'RS',type:'scratch',color:'#56b6ff'},
  {name:'Victory Sting',sub:'Winner moment',icon:'V',type:'victory',color:'#50d890'},
  {name:'Dramatic Hit',sub:'Big reveal impact',icon:'DH',type:'impact',color:'#d96c9d'},
  {name:'Reveal Sparkle',sub:'Magic reveal',icon:'*',type:'sparkle',color:'#f5b942'},
  {name:'TikTok Clip',sub:'Tap to add original clip',icon:'TT',type:'upload',color:'#50d890'}
];
let ctx,master,current=[],deferredPrompt,mediaRecorder,micStream,recordChunks=[]; const $=s=>document.querySelector(s);
function audio(){if(!ctx){ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=+$('#volume').value;master.connect(ctx.destination)}if(ctx.state==='suspended')ctx.resume();return ctx}
function stopAll(){current.forEach(n=>{try{n.stop?.();n.pause?.()}catch{}});current=[];document.querySelectorAll('.playing').forEach(e=>e.classList.remove('playing'))}
function prep(){if(!$('#overlap').checked)stopAll();return audio()}
function noiseBuffer(seconds){const c=audio(),b=c.createBuffer(1,c.sampleRate*seconds,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;return b}
function source(buffer,dest=master){const s=audio().createBufferSource();s.buffer=buffer;s.connect(dest);s.start();current.push(s);s.onended=()=>current=current.filter(x=>x!==s);return s}
function applause(power=1){const c=prep(),dur=Math.max(1.2,3.4*power),mix=c.createGain(),filter=c.createBiquadFilter();filter.type='bandpass';filter.frequency.value=1250;filter.Q.value=.55;mix.connect(filter).connect(master);const bed=c.createBufferSource();bed.buffer=noiseBuffer(dur);const bg=c.createGain();bg.gain.setValueAtTime(.001,c.currentTime);bg.gain.exponentialRampToValueAtTime(.12,c.currentTime+.12);bg.gain.exponentialRampToValueAtTime(.001,c.currentTime+dur);bed.connect(bg).connect(mix);bed.start();current.push(bed);for(let i=0;i<Math.floor(28*power);i++){const t=c.currentTime+Math.random()*dur*.82,osc=c.createOscillator(),g=c.createGain();osc.type='triangle';osc.frequency.value=100+Math.random()*170;g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.22+Math.random()*.16,t+.008);g.gain.exponentialRampToValueAtTime(.001,t+.055+Math.random()*.07);osc.connect(g).connect(mix);osc.start(t);osc.stop(t+.16);current.push(osc)}}
function sarcastic(){prep();[0,.72,1.55,2.45].forEach((delay,i)=>setTimeout(()=>{if(!ctx)return;const c=audio(),t=c.currentTime,o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.value=115+(i%2)*12;g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.55,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+.16);o.connect(g).connect(master);o.start();o.stop(t+.2);current.push(o)},delay*1000))}
function horn(){const c=prep(),t=c.currentTime;[73.4,98,146.8].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.type=i===0?'sawtooth':'square';o.frequency.setValueAtTime(f,t);o.frequency.linearRampToValueAtTime(f*.94,t+1.8);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.18/(i+1),t+.12);g.gain.setValueAtTime(.18/(i+1),t+1.35);g.gain.exponentialRampToValueAtTime(.001,t+2);o.connect(g).connect(master);o.start();o.stop(t+2.1);current.push(o)})}
function buzzer(){const c=prep(),t=c.currentTime;[110,116].forEach(f=>{const o=c.createOscillator(),g=c.createGain();o.type='sawtooth';o.frequency.value=f;g.gain.setValueAtTime(.22,t);g.gain.setValueAtTime(.22,t+.72);g.gain.exponentialRampToValueAtTime(.001,t+.9);o.connect(g).connect(master);o.start();o.stop(t+.92);current.push(o)})}
function boo(){const c=prep(),dur=2.2,n=c.createBufferSource(),filter=c.createBiquadFilter(),g=c.createGain();n.buffer=noiseBuffer(dur);filter.type='lowpass';filter.frequency.value=430;g.gain.setValueAtTime(.001,c.currentTime);g.gain.exponentialRampToValueAtTime(.35,c.currentTime+.15);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+dur);n.connect(filter).connect(g).connect(master);n.start();current.push(n);for(let i=0;i<7;i++){const o=c.createOscillator(),og=c.createGain(),t=c.currentTime+Math.random()*.5;o.type='sawtooth';o.frequency.setValueAtTime(150+Math.random()*80,t);o.frequency.linearRampToValueAtTime(90+Math.random()*40,t+1.4);og.gain.setValueAtTime(.001,t);og.gain.exponentialRampToValueAtTime(.045,t+.1);og.gain.exponentialRampToValueAtTime(.001,t+1.6);o.connect(og).connect(master);o.start(t);o.stop(t+1.7);current.push(o)}}
function laugh(){const c=prep();for(let p=0;p<8;p++){const start=c.currentTime+Math.random()*.45;for(let j=0;j<3+Math.floor(Math.random()*4);j++){const t=start+j*(.12+Math.random()*.1),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(180+Math.random()*260,t);o.frequency.exponentialRampToValueAtTime(110+Math.random()*120,t+.11);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.06+Math.random()*.06,t+.025);g.gain.exponentialRampToValueAtTime(.001,t+.12);o.connect(g).connect(master);o.start(t);o.stop(t+.14);current.push(o)}}}
function tone(freq,start,dur,vol=.18,type='sine',end=freq){const c=audio(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,start);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),start+dur);g.gain.setValueAtTime(.001,start);g.gain.exponentialRampToValueAtTime(vol,start+.01);g.gain.exponentialRampToValueAtTime(.001,start+dur);o.connect(g).connect(master);o.start(start);o.stop(start+dur+.03);current.push(o)}
function splat(){const c=prep(),t=c.currentTime;for(let i=0;i<18;i++)tone(900-i*32,t+i*.055,.12,.07,'sine',500-i*18);setTimeout(()=>{const c2=audio(),n=c2.createBufferSource(),f=c2.createBiquadFilter(),g=c2.createGain();n.buffer=noiseBuffer(.42);f.type='lowpass';f.frequency.value=260;g.gain.setValueAtTime(.45,c2.currentTime);g.gain.exponentialRampToValueAtTime(.001,c2.currentTime+.4);n.connect(f).connect(g).connect(master);n.start();current.push(n)},980)}
function airhorn(){const c=prep(),t=c.currentTime;[220,277,330].forEach((f,i)=>tone(f,t,1.15,.14/(i+1),'sawtooth',f*.96))}
function rimshot(){const c=prep(),t=c.currentTime;tone(145,t,.12,.35,'triangle',80);setTimeout(()=>{const c2=audio(),n=c2.createBufferSource(),f=c2.createBiquadFilter(),g=c2.createGain();n.buffer=noiseBuffer(.18);f.type='highpass';f.frequency.value=2500;g.gain.setValueAtTime(.3,c2.currentTime);g.gain.exponentialRampToValueAtTime(.001,c2.currentTime+.16);n.connect(f).connect(g).connect(master);n.start();current.push(n)},180)}
function gasp(){const c=prep(),t=c.currentTime;for(let i=0;i<10;i++)tone(210+Math.random()*260,t+Math.random()*.2,.55,.045,'sine',390+Math.random()*250)}
function scratch(){const c=prep(),t=c.currentTime;for(let i=0;i<12;i++)tone(1250-i*75,t+i*.025,.09,.075,'sawtooth',500-i*20)}
function victory(){const c=prep(),t=c.currentTime;[523,659,784,1047].forEach((f,i)=>tone(f,t+i*.16,.28,.16,'square',f))}
function impact(){const c=prep(),t=c.currentTime;tone(85,t,1.2,.42,'sine',34);tone(170,t,.65,.13,'sawtooth',55)}
function sparkle(){const c=prep(),t=c.currentTime;[784,988,1175,1568,2093].forEach((f,i)=>tone(f,t+i*.09,.45,.10,'sine',f*1.08))}
function playFile(path){prep();const a=new Audio(path);a.volume=+$('#volume').value;a.onended=()=>current=current.filter(x=>x!==a);a.play();current.push(a)}
function playBuiltin(s){if(s.file)return playFile(s.file);if(s.type==='upload'){toast('Choose the original TikTok audio file');return $('#fileInput').click()}({applause:()=>applause(s.power),sarcastic,boo,laugh,horn,buzzer,splat,airhorn,rimshot,gasp,scratch,victory,impact,sparkle}[s.type])()}
function flash(el){el.classList.add('playing');setTimeout(()=>el.classList.remove('playing'),180)}
function renderBuiltins(){builtins.forEach((s,i)=>{const b=document.createElement('button');b.className='pad';b.style.setProperty('--accent',s.color);b.innerHTML=`<span class="pad-key">${i+1}</span><span class="pad-icon">${s.icon}</span><span class="pad-name">${s.name}</span><span class="pad-sub">${s.sub}</span>`;b.onclick=()=>{flash(b);playBuiltin(s)};$('#builtins').append(b)})}
function renderEmptyPads(){for(let i=1;i<=4;i++){const b=document.createElement('button');b.className='pad';b.style.setProperty('--accent','#464150');b.innerHTML=`<span class="pad-icon">ï¼‹</span><span class="pad-name">Empty pad ${i}</span><span class="pad-sub">Tap to add a sound</span>`;b.onclick=()=>$('#fileInput').click();$('#emptyPads').append(b)}}
const dbp=new Promise((resolve,reject)=>{const r=indexedDB.open('live-button-sounds',1);r.onupgradeneeded=()=>r.result.createObjectStore('sounds',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function allCustom(){const db=await dbp;return new Promise((res,rej)=>{const r=db.transaction('sounds').objectStore('sounds').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function saveCustom(item){const db=await dbp;return new Promise((res,rej)=>{const r=db.transaction('sounds','readwrite').objectStore('sounds').put(item);r.onsuccess=res;r.onerror=()=>rej(r.error)})}
async function deleteCustom(id){const db=await dbp;return new Promise((res,rej)=>{const r=db.transaction('sounds','readwrite').objectStore('sounds').delete(id);r.onsuccess=res;r.onerror=()=>rej(r.error)})}
async function renderCustom(){const wrap=$('#customSounds');wrap.innerHTML='';const items=await allCustom();$('#emptyState').classList.toggle('hidden',items.length>0);items.forEach(item=>{const b=document.createElement('button');b.className='pad custom-pad';b.style.setProperty('--accent','#50d890');b.innerHTML=`<span class="pad-icon">ðŸŽµ</span><span class="pad-name"></span><span class="pad-sub">Custom sound</span><span class="remove" aria-label="Remove sound">Remove</span>`;b.querySelector('.pad-name').textContent=item.name;b.onclick=e=>{if(e.target.classList.contains('remove'))return;prep();const a=new Audio(URL.createObjectURL(item.blob));a.volume=+$('#volume').value;a.onended=()=>{URL.revokeObjectURL(a.src);current=current.filter(x=>x!==a)};a.play();current.push(a);flash(b)};b.querySelector('.remove').onclick=async e=>{e.stopPropagation();if(confirm(`Remove â€œ${item.name}â€?`)){await deleteCustom(item.id);renderCustom();toast('Sound removed')}};wrap.append(b)})}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
async function populateMics(){if(!navigator.mediaDevices?.enumerateDevices)return;const previous=$('#micSelect').value,devices=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='audioinput'),select=$('#micSelect');select.innerHTML='<option value="">Default microphone</option>';devices.forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||`Microphone ${i+1}`;select.append(o)});if([...select.options].some(o=>o.value===previous))select.value=previous;return devices}
async function setupMics(){try{const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(t=>t.stop());const devices=await populateMics();toast(devices?.length?`${devices.length} microphone input${devices.length===1?'':'s'} found`:'No microphone inputs found')}catch(err){toast(err?.name==='NotAllowedError'?'Allow microphone access to choose an input':'Could not find microphones')}}
async function toggleRecording(){const btn=$('#recordBtn');if(mediaRecorder?.state==='recording'){mediaRecorder.stop();btn.textContent='â— Record clip';return}try{const deviceId=$('#micSelect').value;micStream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:deviceId?{exact:deviceId}:undefined,echoCancellation:false,noiseSuppression:false,autoGainControl:false}});await populateMics();recordChunks=[];const preferred=['audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));mediaRecorder=new MediaRecorder(micStream,preferred?{mimeType:preferred}:undefined);mediaRecorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data)};mediaRecorder.onstop=async()=>{micStream?.getTracks().forEach(t=>t.stop());const blob=new Blob(recordChunks,{type:mediaRecorder.mimeType||'audio/webm'});if(blob.size<1000){toast('Recording was too short');return}const suggested=`Mic clip ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`;const name=prompt('Name this soundboard clip:',suggested);if(!name)return;try{await saveCustom({id:crypto.randomUUID(),name:name.trim()||suggested,blob});await renderCustom();toast('Recording added to My sounds')}catch{toast('Could not save the recording')}};mediaRecorder.start();btn.textContent='â–  Stop recording';toast(`Recording from ${micStream.getAudioTracks()[0]?.label||'selected microphone'}â€¦`)}catch(err){toast(err?.name==='NotAllowedError'?'Microphone permission was not allowed':err?.name==='OverconstrainedError'?'That microphone is no longer connected':'Microphone is unavailable')}}
$('#fileInput').onchange=async e=>{for(const file of e.target.files){if(!file.type.startsWith('audio/'))continue;try{await saveCustom({id:crypto.randomUUID(),name:file.name.replace(/\.[^.]+$/,''),blob:file})}catch{toast('Not enough device storage for that sound')}}e.target.value='';await renderCustom();toast('Sounds added')};
$('#volume').oninput=e=>{if(master)master.gain.value=+e.target.value};$('#stopBtn').onclick=stopAll;window.addEventListener('keydown',e=>{if(e.repeat||e.target.matches('input'))return;const i=Number(e.key)-1;if(i>=0&&i<builtins.length){document.querySelectorAll('#builtins .pad')[i].click()}if(e.key==='Escape')stopAll()});
$('#recordBtn').onclick=toggleRecording;
$('#micSetupBtn').onclick=setupMics;if(navigator.mediaDevices){navigator.mediaDevices.addEventListener?.('devicechange',populateMics);populateMics()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});$('#installBtn').onclick=async()=>{if(!deferredPrompt){alert('On Chromebook: open Chromeâ€™s three-dot menu, choose Cast, save, and share, then Install page as app. If that choice is missing, reload this page once and try again.');return}deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null};
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js?v=7',{updateViaCache:'none'});renderBuiltins();renderEmptyPads();renderCustom();

